### PR TITLE
added check for inlineImage name of images

### PR DESCRIPTION
**Pull request by janeznovak**
Added the check for images of name imageInline for ckeditor5.
The event didn't return any images, because it checked only for the name "image", but in ckeditor5 you can also have "imageInline".

Edit: changed inlineImage to imageInline, which is the correct name.

### CODE REVIEW

**Comment by shibbirweb** [comment]
@janeznovak Thanks for contributing to this plugin. 
Can you please give an example of an inline image? so, that I can confirm your changes.

**Comment by janeznovak** [comment]
I can give you the link to the official documentation of ckeditor5, https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html. Otherwise all i do is upload an image from my computer to the ckeditor. The picture: 
image
which gets sent to my server. When I logged out the name, it was inlineImage and not image.

**Comment by shibbirweb** [comment]
> I can give you the link to the official documentation of ckeditor5, https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html. Otherwise all i do is upload an image from my computer to the ckeditor. The picture: image which gets sent to my server. When I logged out the name, it was inlineImage and not image.

can you upload a demo project and console log everything?

**Comment by janeznovak** [comment]
That would take some time, because it is a commercial product with strapi, so I would neet to delete all the entities in it, and probably can't even share the code. So that would mean that I would need to make a smaller project at home with bare minimum code. As I said, I can do that, it will just take some time.

**Comment by shibbirweb** [comment]
> That would take some time, because it is a commercial product with strapi, so I would neet to delete all the entities in it, and probably can't even share the code. So that would mean that I would need to make a smaller project at home with bare minimum code. As I said, I can do that, it will just take some time.

just create a demo repository. no need real data or server. Just add HTML with cdn image link and apply plugin

**Comment by janeznovak** [comment]
Will try at home.

**Comment by shibbirweb** [comment]
> Will try at home.

Okay. Thanks for contributing.

**Comment by janeznovak** [comment]
My pleasure. Hope it'll help.

**Comment by janeznovak** [comment]
OK, so I made a Vue app with ckeditor and your plugin. I put it in my repo. Here is the link to it: https://github.com/janeznovak/ckeditor5-image-remove-event-callback-plugin/tree/demo1. You have the steps to install the app and reproduce the "problem"(if we can call it that) in the readme.

**Comment by shibbirweb** [comment]
> OK, so I made a Vue app with ckeditor and your plugin. I put it in my repo. Here is the link to it: https://github.com/janeznovak/ckeditor5-image-remove-event-callback-plugin/tree/demo1. You have the steps to install the app and reproduce the "problem"(if we can call it that) in the readme.

I will check and confirm. If your changes ok then I will merge. (Sorry for late response.)

**Comment by shibbirweb** [comment]
> OK, so I made a Vue app with ckeditor and your plugin. I put it in my repo. Here is the link to it: https://github.com/janeznovak/ckeditor5-image-remove-event-callback-plugin/tree/demo1. You have the steps to install the app and reproduce the "problem"(if we can call it that) in the readme.

Your suggestion is right. I merge your pull request. Thanks for your valuable contribution.

**Comment by janeznovak** [comment]
> > OK, so I made a Vue app with ckeditor and your plugin. I put it in my repo. Here is the link to it: https://github.com/janeznovak/ckeditor5-image-remove-event-callback-plugin/tree/demo1. You have the steps to install the app and reproduce the "problem"(if we can call it that) in the readme.
> 
> Your suggestion is right. I merge your pull request. Thanks for your valuable contribution.

Happy to do it:smiley:

**Pull request merged**
